services:
  database:
    image: postgres
    container_name: CBV_DB
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: CBV_APP
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local
